### ISSUE TITLE
geometrie, nauwkeurigheid, schaalniveaus

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/StOP#3]
Vraag van Wideke

hoe gaan we om met verschillende schaalniveau’s
hoe gaan we om met nauwkeurigheid?
hoe gaan we om met temporele werkingsgebieden?
hoe kunnen we deze kwaliteitseisen opslaan in het model?

**Comment by wilkoquak** [comment]
Op zich allemaal vragen die nog steeds spelen, maar hier op github worden ze niet opgelost. Ik denk dat ze in Jira moeten. Ik sluit deze isssue even.
